# Required source files for this test
set( test_srcs ${PROJECT_SOURCE_DIR}/src/Exception.cpp
			   ${PROJECT_SOURCE_DIR}/src/Node.cpp
			   ${PROJECT_SOURCE_DIR}/src/MovableObject.cpp
			   ${PROJECT_SOURCE_DIR}/src/PropertyCollection.cpp
			   ${PROJECT_SOURCE_DIR}/plugins/ODE/Space.cpp
			   ${PROJECT_SOURCE_DIR}/plugins/ODE/Geom.cpp
			   ${PROJECT_SOURCE_DIR}/src/math/Util.cpp
			   ${PROJECT_SOURCE_DIR}/src/math/Quaternion.cpp
			   ${PROJECT_SOURCE_DIR}/src/math/MathExpression.cpp )